language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
script:
  - flake8 hook/__init__.py
  - flake8 hook/models.py
  - flake8 hook/forms.py
  - flake8 hook/routes/auth.py
  - flake8 hook/routes/chat.py
  - flask test